name: "Send Slack notification"
description: "Use slack api to send notification as custom username/icon"
inputs:
  token:
    description: "Slack bot token (xoxb-....)"
    required: true
  username:
    description: "The project thats being built"
    default: "Deployer"
  icon_url:
    description: "The project's icon"
runs:
  using: composite
  steps:
    - run: |
        curl -d "text=HEllo world" -d "channel=C04TAEX1RC1" -d "username=${{ inputs.username }}" -d "icon_url=${{ inputs.icon_url }}" -H "Authorization: Bearer ${{ inputs.token }}" -X POST https://slack.com/api/chat.postMessage
      shell: bash
