name: "Send Slack notification"
description: "Use slack api to send notification as custom username/icon"
inputs:
  token:
    description: "Slack bot token (xoxb-....)"
    required: true
  channel:
    description: "the channel to post to"
    required: true
  username:
    description: "The project thats being built"
    default: "Deployer"
  icon_url:
    description: "The project's icon"
    default: "https://deployer.org/img/logo.svg"
  message: 
    description: "the main message to send"
    required: true
  type:
    description: "commit: shows commit info | plain: only a message"
    default: 'commit'

runs:
  using: composite
  steps:
    - run: |
        echo "message=\"$(git log --format=%B -n 1 HEAD | tr '\n' ' ')\"" >> $GITHUB_OUTPUT
        echo "author=\"$(git log --format=%an -n1 HEAD)\"" >> $GITHUB_OUTPUT
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      shell: bash
      id: info

    - if: ${{ inputs.type == 'commit' }}
      run: |
        curl --data '{
          "channel": "${{ inputs.channel }}",
          "username": "${{ inputs.username }}",
          "icon_url": "${{ inputs.icon_url }}",
          "blocks": [
            {"type": "section", "text": {"type": "mrkdwn", "text": "${{ inputs.message }}"}},
            {"type": "section", "fields": [{"type": "mrkdwn", "text": "*Commit*:\n <${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.info.outputs.sha }}|${{ steps.info.outputs.message}}>"}, {"type": "mrkdwn", "text": "*Author*:\n ${{ steps.info.outputs.author}}"}]},
            {"type": "divider"}
          ]
        }' \
        -H "Content-type: application/json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        -X POST https://slack.com/api/chat.postMessage
      shell: bash

    - if: ${{ inputs.type == 'plain' }}
      run: |
        curl --data '{
          "channel": "${{ inputs.channel }}",
          "username": "${{ inputs.username }}",
          "icon_url": "${{ inputs.icon_url }}",
          "blocks": [
            {"type": "section", "text": {"type": "mrkdwn", "text": "${{ inputs.message }}"}},
            {"type": "divider"}
          ]
        }' \
        -H "Content-type: application/json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        -X POST https://slack.com/api/chat.postMessage
      shell: bash
