name: "Send Slack notification"
description: "Use slack api to send notification as custom username/icon"
inputs:
  token:
    description: "Slack bot token (xoxb-....)"
    required: true
  username:
    description: "The project thats being built"
    default: "Deployer"
  icon_url:
    description: "The project's icon"
runs:
  using: composite
  steps:
    - run: echo hello world
      shell: bash
    - run: echo ${{ inputs.username }}
      shell: bash
