on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: mattydebie/ut-slack@main
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          username: matty
          icon_url: https://ca.slack-edge.com/TCKAFJV8Q-U01QDBQBB9T-5568bb1ffb89-512
          channel: C04TAEX1RC1
          message: "New build is ready"

      - uses: mattydebie/ut-slack@main
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          username: Van Marcke
          icon_url: https://ca.slack-edge.com/TCKAFJV8Q-U01QDBQBB9T-5568bb1ffb89-512
          channel: C04TAEX1RC1
          message: "New deploy to *DEV*"
          type: plain
